/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthBg: typeof import('./src/components/auth/AuthBg.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    FormLogin: typeof import('./src/components/auth/FormLogin.vue')['default']
    FormRegister: typeof import('./src/components/auth/FormRegister.vue')['default']
    FormTitle: typeof import('./src/components/auth/FormTitle.vue')['default']
    Message: typeof import('./src/components/auth/Message.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
  }
}
